# Docker Compose file for CircuitHub development environment
version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: circuithub_db
    environment:
      POSTGRES_DB: circuithub
      POSTGRES_USER: circuithub_user
      POSTGRES_PASSWORD: circuithub_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U circuithub_user -d circuithub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional for future use)
  redis:
    image: redis:7-alpine
    container_name: circuithub_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Next.js application
  app:
    build: .
    container_name: circuithub_app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://circuithub_user:circuithub_password@postgres:5432/circuithub?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-here
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: